theme = "dracula"

[editor]
scrolloff = 8
line-number = "relative"
auto-pairs = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = true

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"]

